
sources:
  - name: raw
    database: FUSION_UPGRADE_DB
    schema: RAW
    tables:
      - name: us_west_sales
        config:
          freshness: 
          error_after:
            count: 1
            period: minute 
      - name: us_east_sales
        config:
          freshness: 
          error_after:
            count: 1
            period: day 